### ISSUE TITLE
build-all fails: build-docs command not found

### ISSUE THREAD

**Issue by laurent-simon** [sharat87/prestige#14]
`./manage build-all` gives the following error: 

```txt
./manage: line 232: build-docs: command not found
```

Something is missing...

**Comment by sharat87** [comment]
Hey, thanks for pointing out. I fixed this only yesterday but forgot to push. It should be there now, can you check again please?

**Comment by laurent-simon** [comment]
It's ok for this one, but now, after the build, `./manage start` give the following error:

```txt
Traceback (most recent call last):
  File "/home/dev/prestige/venv/bin/supervisord", line 5, in <module>
    from supervisor.supervisord import main
ModuleNotFoundError: No module named 'supervisor'
```

**Comment by sharat87** [comment]
Already fixed.
