### ISSUE TITLE
Oauth request to github for gist integration is requesting access to public and private repos

### ISSUE THREAD

**Issue by NeilsC** [sharat87/prestige#16]
When connecting prestige to github for gist integration, prestige is requesting access to all of my public and private repos. Is this necessary?

![image](https://user-images.githubusercontent.com/1214412/152466906-4b1cede9-2002-45dc-8320-8fe178cb95b2.png)

**Comment by sharat87** [comment]
Hey @NeilsC, thanks for asking. Yes, this can be removed. Opening files from repositories was also part of the original scope of the GitHub integration feature, but then I figured I'll ship just Gist now and implement repo integration later, but I never went back and changed this. I'll add the `repo` permission in the scope when repo integration feature is actually implemented, I think that should be okay.

Would you be interested in opening a PR for this? It's removing `repo` from this line of scopes requested:

https://github.com/sharat87/prestige/blob/668e771c73476a54ecc5186ead447f0cd49b21b7/backend/auth_api/views.py#L210

Or I can get to it soon. 😄

**Comment by NeilsC** [comment]
Here you go: https://github.com/sharat87/prestige/pull/17
