### ISSUE TITLE
Server is down after unhandled error on BE side

### ISSUE THREAD

**Issue by v-honcharenko** [sharat87/prestige#18]
It seems like there is no global error handling. 
So after some error, I got after the request to create a gist, the site was shut down.

![image](https://user-images.githubusercontent.com/12469814/186191443-63457027-dcc4-490b-8119-240b24fe4e36.png)

**Comment by sharat87** [comment]
Hey, thank you for reporting this. I've added a panic recovery to the backend server, as well as resolved the underlying problem that was causing this. You shouldn't see this problem here on.

Thanks for your support. :)
