### ISSUE TITLE
JWT Example

### ISSUE THREAD

**Issue by dominiquefournier** [sharat87/prestige#7]
I would like to use Prestige in the following steps : 
1. Send a POST to login page with user password in headers
2. GET a JWT Token as result of the previous body request (and store it)
3. Use the JWT on following requests in headers with "Authorization: Bearer YYYY".

Of course, the JWT change every time you try to authenticate on step 1.

Is there a way to do that ? It should be documented for everyone as the JWT is often used.
Thanks

**Comment by sharat87** [comment]
Hey @dominiquefournier, thank you for writing.

This is unfortunately not possible today. I'm currently working on response handler scripts that will let us write a small Javascript function, which will be called with the response of a request. This function can then save the JWT somewhere (`localStorage` perhaps), and can be loaded for any subsequent requests.

Until the response handler scripts support is out though, the best approach is to copy the JWT from the response and put it in a data field in a Javascript block and use from there. It needs to be updated everytime we get a new JWT though.

Example:

```
### javascript
// Update the token value here, when we get a new token.
this.data.jwt = "my-jwt-value"

###

GET https://httpbun.com/bearer
Authorization: Bearer ${jwt}

```

This is a workaround for this, until we have response-handler-scripts. I'll keep this issue open until I finish and release that feature.

**Comment by dominiquefournier** [comment]
Maybe no need to store the token somewhere, just allow it value to be reused. But I understand you need to read the answer from the server and analyze it.

**Comment by sharat87** [comment]
Yes, the store part needs some thought. But `localStorage` is at least a workaround to do this, if only we had response-handler scripts.

**Comment by sharat87** [comment]
Hey @dominiquefournier, just pushed an update that'll make this possible. This is yet to be documented and is in very initial stages (considering I _just_ pushed :wink:)

```
GET https://httpbun.com/bearer
Authorization: Bearer ${this.loadItem("myJwt")}

###

POST https://httpbun.com/post
Content-Type: application/x-www-form-urlencoded

jwt=dummy-token

@onFinish(result) {
	console.log(JSON.parse(result.response.body).form.name)
	this.storeItem("myJwt", JSON.parse(result.response.body).form.jwt)
}
```

How to get the JWT from the response body in the second request above will depend on the response structure of the API call you are making. But the idea is, in the finish handler for the request that produces the JWT, we store it using `.storeItem` and for all other requests that need this JWT, we load it using `.loadItem`.

This data is stored in the browser `localStorage`, and can bee inspected from the browser devtools. Keys start with `pstore:`.

I'll improve the API in the coming weeks, but we have a solution now. Please try this out and let me know how it goes. Thanks!

If you face any problems, please reopen this issue or open a new issue.
